name: flutter_ble_lib
description: FlutterBle Library is a flutter library that supports BLE operations. It uses MultiPlatformBleAdapter as a native backend..
version: 2.1.0
author: "Polidea <hello@polidea.com>"
homepage: https://github.com/Polidea/FlutterBleLib

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  collection: ^1.14.1
  async: ^2.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.3
  mockito: ^4.1.1

  flutter_test:
    sdk: flutter


flutter:

  plugin:
    androidPackage: com.polidea.flutter_ble_lib
    pluginClass: FlutterBleLibPlugin

