name: flutter_ble_lib
description: A new flutter plugin project.
version: 1.0.0-SNAPSHOT
author: Polidea
#TODO change it after migration on github
hompage: https://gitlab2.polidea.com/Internal/flutter-ble-lib/

flutter:
  plugin:
    androidPackage: com.polidea.flutterblelib
    pluginClass: FlutterBleLibPlugin

dependencies:
  flutter:
    sdk: flutter
  convert: "^2.0.1"
  protobuf: '^0.5.5'


